language: groovy
language: groovy

jdk:
  - oraclejdk7

before_install:
- curl -s http://get.sdkman.io | bash
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails 3.1.7

script: grails test-app --stacktrace